package com.test.my.app.common.constants

object NavigationConstants {
    var APPID = "com.test.my.app.uat"
    const val HOME = "com.test.my.app.home.ui.HomeMainActivity"

//    const val LOGIN = "com.test.my.app.security.ui.SecurityActivity"
    const val SPLASH_SCREEN = "com.test.my.app.security.ui.SplashScreenActivity"
    const val TERMS_POLICY_SCREEN = "com.test.my.app.security.ui.TermsAndPolicyActivity"
    const val SETTINGS = "com.test.my.app.home.ui.SettingsActivity"
    const val TERMS_CONDITION = "com.test.my.app.home.ui.TermsConditionActivity"
    const val FAMILY_PROFILE = "com.test.my.app.home.ui.ProfileAndFamilyMember.FamilyProfileActivity"
    const val BLOG_DETAIL = "com.test.my.app.home.ui.BlogDetailActivity"
    const val PASSWORD_CHANGE = "com.test.my.app.home.ui.PasswordChangeActivity"
    const val FITNESS_BROADCAST_RECEIVER = "com.test.my.app.fitness_tracker.receiver.FitnessBroadcastReceiver"

    const val LANGUAGE_SCREEN = "com.test.my.app.home.ui.LanguageActivity"
    const val SUD_LIFE_POLICY = "com.test.my.app.home.ui.sudLifePolicy.SudLifePolicyActivity"
    const val SUD_LIFE_POLICY_AUTHENTICATION = "com.test.my.app.home.ui.sudLifePolicy.SudPolicyAuthenticationActivity"
    const val FEED_UPDATE_SCREEN = "com.test.my.app.home.ui.WebViews.FeedUpdateActivity"
    const val SALT_WEB_VIEW_SCREEN = "com.test.my.app.home.ui.WebViews.SaltWebViewActivity"
    const val NIMEYA_WEB_VIEW_SCREEN = "com.test.my.app.home.ui.nimeya.NimeyaWebViewActivity"
    const val AMAHA_WEB_VIEW_SCREEN = "com.test.my.app.home.ui.WebViews.AmahaWebViewActivity"
    const val LEADERSHIP_EXPERINCES_SCREEN = "com.test.my.app.home.ui.WebViews.LeadershipExperincesActivity"
    const val GENERAL_WEB_NOTIFICATION_SCREEN = "com.caressa.home.ui.WebViews.GeneralWebNotificationActivity"
    const val WELLFIE_SCREEN = "com.test.my.app.home.ui.wellfie.WellfieActivity"
    const val WELLFIE_RESULT_SCREEN = "com.test.my.app.home.ui.wellfie.WellfieResultActivity"
    const val BMI_VITALS_SCREEN = "com.test.my.app.home.ui.wellfie.BmiVitalsActivity"
    const val NIMEYA_SCREEN = "com.test.my.app.home.ui.nimeya.NimeyaActivity"
    const val FITROFY_SDP_SCREEN = "com.test.my.app.home.ui.WebViews.FitrofySdpActivity"

    const val BEGIN_VITALS_ACTIVITY = "com.test.my.app.wyh.faceScan.ui.BeginVitalsActivity"
    const val FACE_SCAN_ACTIVITY = "com.test.my.app.wyh.faceScan.ui.FaceScanActivity"
    const val FACE_SCAN_RESULT_ACTIVITY = "com.test.my.app.wyh.faceScan.ui.FaceScanResultActivity"

    const val HEALTH_CONTENT_DASHBOARD_ACTIVITY = "com.test.my.app.wyh.healthContent.ui.HealthContentDashboardActivity"
    const val HEALTH_CONTENT_DETAILS_ACTIVITY = "com.test.my.app.wyh.healthContent.ui.HealthContentDetailsActivity"

    const val WYH_IRA_QUESTIONS_ACTIVITY = "com.test.my.app.wyh.ira.ui.IraQuestionPagerActivity"
    const val WYH_IRA_SUMMARY_ACTIVITY = "com.test.my.app.wyh.ira.ui.IraSummaryReportActivity"

    const val WYH_HRA_QUESTIONS_ACTIVITY = "com.test.my.app.wyh.hra.ui.QuestionPagerActivity"
    const val WYH_HRA_SUMMARY_ACTIVITY = "com.test.my.app.wyh.hra.ui.SummaryReportActivity"

    const val FITNESS_TRACKER = "com.test.my.app.fitness_tracker.ui.FitnessDataActivity"
    const val WATER_TRACKER = "com.test.my.app.water_tracker.WaterTrackerActivity"
    const val MEDICINE_TRACKER = "com.test.my.app.medication_tracker.MedicationHomeActivity"
    const val STORE_RECORDS = "com.test.my.app.records_tracker.HealthRecordsActivity"
    const val WATER_TRACKER_HOME = "com.test.my.app.water_tracker.WaterTrackerActivity"
    const val FITNESS_HOME = "com.test.my.app.fitness_tracker.ui.FitnessDataActivity"
    const val TOOLS_CALCULATORS_HOME = "com.test.my.app.tools_calculators.ToolsCalculatorsHomeActivity"
    const val BLOGS_HOME = "com.test.my.app.blogs.BlogsActivity"
    const val TRACK_PARAMETER_HOME = "com.test.my.app.track_parameter.ParameterHomeActivity"
    const val HEALTH_LIBRARY = "com.test.my.app.blogs.BlogsActivity"
    const val HRA_SUMMARY = "com.test.my.app.hra.ui.HraSummaryActivity"
    const val HRA_HOME = "com.test.my.app.hra.HraHomeActivity"
    const val HRA_INFO = "com.test.my.app.hra.ui.HraInfoActivity"
    const val AKTIVO_PERMISSION_SCREEN = "com.test.my.app.home.ui.aktivo.AktivoPermissionsActivity"
    const val EDIT_PROFILE_ACTIVITY = "com.test.my.app.home.ui.ProfileAndFamilyMember.EditProfileActivity"
    const val PARAMETER_HOME_ACTIVITY = "com.test.my.app.track_parameter.ParameterHomeActivity"
}